app:
  title: ForgePath
  baseUrl: http://localhost:3000
  packages: all
  routes:
    bindings:
      scaffolder.registerComponent: false
  extensions:
    - page:catalog:
        config:
          path: /

organization:
  name: ForgePath

backend:
  baseUrl: http://localhost:7007
  listen:
    host: 127.0.0.1
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, POST]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  providers:
    guest: {}

permission:
  enabled: true

catalog:
  rules:
    - allow: [Component, Group, Resource, System, Template]
  locations:
    - type: file
      target: ../../catalog/entities.yaml
      rules:
        - allow: [Group, Resource, System]
    - type: file
      target: ../../../../services/secure-fastapi-service/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: file
      target: ../../../../templates/secure-fastapi-service/template.yaml
      rules:
        - allow: [Template]

scaffolder:
  defaultAuthor:
    name: ForgePath
    email: forgepath@invalid.example

forgepath:
  repositoryRoot: ../..
  generationRoot: ../../.forgepath/generated
  simulationRoot: ../../.forgepath/published
  pythonExecutable: python3.12
  allowedOwners:
    - group:default/platform
  allowedSystems:
    - forgepath
  allowedRepositoryOwners:
    - SecureCloudOps
  gitopsRepository: SecureCloudOps/forgepath-gitops
  githubCodeowner: SecureCloudOps/platform
  catalogApiUrl: http://localhost:7007/api/catalog

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

kubernetes:
  frontend:
    podDelete:
      enabled: false
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: localKubectlProxy
  objectTypes:
    - deployments
    - pods
    - replicasets
    - services
    - statefulsets
    - daemonsets
    - jobs
    - cronjobs
  customResources:
    - group: argoproj.io
      apiVersion: v1alpha1
      plural: applications
