#!/usr/bin/env python3
"""Render the secure FastAPI service template without external dependencies."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

TOKEN_PATTERN = re.compile(r"__FORGEPATH_[A-Z0-9_]+__")
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9-]{1,61}[a-z0-9]$")
REPLACEMENTS = {
    "__FORGEPATH_SERVICE_NAME__": "service_name",
    "__FORGEPATH_SERVICE_DESCRIPTION__": "description",
    "__FORGEPATH_OWNER__": "owner",
    "__FORGEPATH_KUBERNETES_NAMESPACE__": "kubernetes_namespace",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--service-name", default="example-fastapi")
    parser.add_argument(
        "--description", default="A secure FastAPI service generated by ForgePath."
    )
    parser.add_argument("--owner", default="group:default/platform")
    parser.add_argument(
        "--kubernetes-namespace",
        help="Namespace recorded in Backstage metadata (defaults to <service-name>-local)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not NAME_PATTERN.fullmatch(args.service_name):
        raise SystemExit("service name must be a 3-63 character DNS label")
    if args.kubernetes_namespace is None:
        args.kubernetes_namespace = f"{args.service_name}-local"
    if not NAME_PATTERN.fullmatch(args.kubernetes_namespace):
        raise SystemExit("Kubernetes namespace must be a 3-63 character DNS label")
    if args.output.exists() and any(args.output.iterdir()):
        raise SystemExit(f"output directory is not empty: {args.output}")

    source = Path(__file__).resolve().parent / "skeleton"
    args.output.mkdir(parents=True, exist_ok=True)
    values = vars(args)

    for source_path in sorted(source.rglob("*")):
        relative = source_path.relative_to(source)
        target = args.output / relative
        if source_path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        rendered = source_path.read_text(encoding="utf-8")
        for token, argument in REPLACEMENTS.items():
            rendered = rendered.replace(token, str(values[argument]))
        unresolved = TOKEN_PATTERN.findall(rendered)
        if unresolved:
            raise SystemExit(f"unresolved template token in {relative}: {unresolved[0]}")
        target.write_text(rendered, encoding="utf-8")

    shutil.copymode(source, args.output)


if __name__ == "__main__":
    main()
