#!/usr/bin/env python3
"""Render the secure FastAPI service template without external dependencies."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

TOKEN_PATTERN = re.compile(r"__FORGEPATH_[A-Z0-9_]+__")
NAME_PATTERN = re.compile(r"^[a-z][a-z0-9-]{1,61}[a-z0-9]$")
OWNER_PATTERN = re.compile(r"^group:default/[a-z][a-z0-9-]{1,61}[a-z0-9]$")
APPROVED_ENVIRONMENTS = ("local", "development", "staging", "production")
APPROVED_CLASSIFICATIONS = ("public", "internal", "confidential", "restricted")
REPLACEMENTS = {
    "__FORGEPATH_SERVICE_NAME__": "service_name",
    "__FORGEPATH_SERVICE_DESCRIPTION__": "description",
    "__FORGEPATH_OWNER__": "owner",
    "__FORGEPATH_OWNER_LABEL__": "owner_label",
    "__FORGEPATH_SYSTEM__": "system",
    "__FORGEPATH_ENVIRONMENT__": "environment",
    "__FORGEPATH_DATA_CLASSIFICATION__": "data_classification",
    "__FORGEPATH_IMAGE_REPOSITORY__": "image_repository",
    "__FORGEPATH_GITHUB_CODEOWNER__": "github_codeowner",
    "__FORGEPATH_GITOPS_REPOSITORY__": "gitops_repository",
    "__FORGEPATH_KUBERNETES_NAMESPACE__": "kubernetes_namespace",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--service-name", default="example-fastapi")
    parser.add_argument(
        "--description", default="A secure FastAPI service generated by ForgePath."
    )
    parser.add_argument("--owner", default="group:default/platform")
    parser.add_argument("--system", default="forgepath")
    parser.add_argument("--environment", choices=APPROVED_ENVIRONMENTS, default="local")
    parser.add_argument(
        "--data-classification", choices=APPROVED_CLASSIFICATIONS, default="internal"
    )
    parser.add_argument(
        "--image-repository",
        help="Immutable image repository (defaults to ghcr.io/securecloudops/<service>)",
    )
    parser.add_argument("--github-codeowner", default="SecureCloudOps/platform")
    parser.add_argument(
        "--gitops-repository", default="SecureCloudOps/forgepath-gitops"
    )
    parser.add_argument(
        "--privileged",
        action="store_true",
        help="Rejected: privileged workloads are outside this paved path",
    )
    parser.add_argument(
        "--kubernetes-namespace",
        help="Namespace recorded in Backstage metadata (defaults to <service-name>-local)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not NAME_PATTERN.fullmatch(args.service_name):
        raise SystemExit("service name must be a 3-63 character DNS label")
    if args.privileged:
        raise SystemExit("privileged access is not supported by this paved path")
    if args.kubernetes_namespace is None:
        args.kubernetes_namespace = f"{args.service_name}-local"
    if not NAME_PATTERN.fullmatch(args.kubernetes_namespace):
        raise SystemExit("Kubernetes namespace must be a 3-63 character DNS label")
    if not OWNER_PATTERN.fullmatch(args.owner):
        raise SystemExit("owner must be a group:default/<dns-label> entity reference")
    args.owner_label = args.owner.rsplit("/", maxsplit=1)[-1]
    if not NAME_PATTERN.fullmatch(args.system):
        raise SystemExit("system must be a 3-63 character DNS label")
    if args.image_repository is None:
        args.image_repository = f"ghcr.io/securecloudops/{args.service_name}"
    expected_image_suffix = f"/{args.service_name}"
    if not args.image_repository.startswith("ghcr.io/") or not args.image_repository.endswith(
        expected_image_suffix
    ):
        raise SystemExit(
            "image repository must use ghcr.io and end with the generated service name"
        )
    expected_github_prefix = args.image_repository.split("/", maxsplit=2)[1] + "/"
    if not args.github_codeowner.casefold().startswith(expected_github_prefix.casefold()):
        raise SystemExit("GitHub CODEOWNER must belong to the allowlisted repository owner")
    if args.gitops_repository.casefold() != (
        f"{expected_github_prefix}forgepath-gitops".casefold()
    ):
        raise SystemExit("GitOps repository must belong to the allowlisted repository owner")
    if args.output.exists() and any(args.output.iterdir()):
        raise SystemExit(f"output directory is not empty: {args.output}")

    source = Path(__file__).resolve().parent / "skeleton"
    args.output.mkdir(parents=True, exist_ok=True)
    values = vars(args)

    for source_path in sorted(source.rglob("*")):
        relative = source_path.relative_to(source)
        target = args.output / relative
        if source_path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            continue
        rendered = source_path.read_text(encoding="utf-8")
        for token, argument in REPLACEMENTS.items():
            rendered = rendered.replace(token, str(values[argument]))
        unresolved = TOKEN_PATTERN.findall(rendered)
        if unresolved:
            raise SystemExit(f"unresolved template token in {relative}: {unresolved[0]}")
        target.write_text(rendered, encoding="utf-8")

    shutil.copymode(source, args.output)


if __name__ == "__main__":
    main()
