apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: forgepath-local
  namespace: argocd
spec:
  description: Restricted project for the ForgePath local paved path
  sourceRepos:
    - git@github.com:SecureCloudOps/ForgePath.git
  destinations:
    - namespace: secure-fastapi-service-local
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: argoproj.io
      kind: AnalysisTemplate
    - group: argoproj.io
      kind: Rollout
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: monitoring.coreos.com
      kind: PrometheusRule
    - group: monitoring.coreos.com
      kind: ServiceMonitor
  clusterResourceBlacklist:
    - group: "*"
      kind: "*"
