apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: forgepath-local
  namespace: argocd
spec:
  description: Restricted project for the ForgePath local paved path
  sourceRepos:
    - git@github.com:SecureCloudOps/ForgePath.git
  destinations:
    - namespace: secure-fastapi-service-local
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: networking.k8s.io
      kind: NetworkPolicy
  clusterResourceBlacklist:
    - group: "*"
      kind: "*"
