{{- if or .Values.networkPolicy.allowIngress .Values.monitoring.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "service.fullname" . }}-allow-ingress
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.allowIngress }}
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
    {{- if .Values.monitoring.enabled }}
    - from:
        - namespaceSelector:
            {{- toYaml .Values.monitoring.prometheusAccess.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.monitoring.prometheusAccess.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
{{- end }}
