apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: {{ .Values.namespaceProtection.limitRange.defaultRequestCpu | quote }}
        memory: {{ .Values.namespaceProtection.limitRange.defaultRequestMemory | quote }}
      default:
        cpu: {{ .Values.namespaceProtection.limitRange.defaultCpu | quote }}
        memory: {{ .Values.namespaceProtection.limitRange.defaultMemory | quote }}
      min:
        cpu: {{ .Values.namespaceProtection.limitRange.minCpu | quote }}
        memory: {{ .Values.namespaceProtection.limitRange.minMemory | quote }}
      max:
        cpu: {{ .Values.namespaceProtection.limitRange.maxCpu | quote }}
        memory: {{ .Values.namespaceProtection.limitRange.maxMemory | quote }}
      maxLimitRequestRatio:
        cpu: {{ .Values.namespaceProtection.limitRange.maxCpuLimitRequestRatio | quote }}
        memory: {{ .Values.namespaceProtection.limitRange.maxMemoryLimitRequestRatio | quote }}
