apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.namespaceProtection.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.namespaceProtection.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.namespaceProtection.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.namespaceProtection.resourceQuota.limitsMemory | quote }}
    pods: {{ .Values.namespaceProtection.resourceQuota.pods | quote }}
    services: {{ .Values.namespaceProtection.resourceQuota.services | quote }}
    configmaps: {{ .Values.namespaceProtection.resourceQuota.configMaps | quote }}
